### ISSUE TITLE
P_t distribution in the light quark sample

### ISSUE THREAD

**Issue by kaechb** [jet-net/JetNet#18]
Hi, 
First off thanks for the nice repo. 
Could it be that there is something wrong with the light quark dataset on zenodo (I only checked 0.1,1.0,1.1, which are the same).
If we plot the $p_T$ for the different particles we get significantly different plots for q than g and t:
![image](https://user-images.githubusercontent.com/38372086/187904975-27b6c757-8689-4c69-88b9-53700c482d18.png)
fig,ax=plt.subplots(5,6,figsize=(20,20))
The code for the plots is here:
```
for i in range(30):
    _,bins,_=ax[i//6,i%6].hist(t[:,i,2],bins=40,label="t",histtype="step",density=1)
    ax[i//6,i%6].hist(q[:,i,2],bins=bins,label="q",histtype="step",density=1)
    ax[i//6,i%6].hist(g[:,i,2],bins=bins,label="g",histtype="step",density=1)
    ax[i//6,i%6].legend()
    #ax[i//6,i%6].set_yscale("log")
plt.suptitle(r"Jet Particles ordered by $p_T$ distribution")
plt.tight_layout()
plt.show()
``` 
We do not expect the $p_T$ to be that different right?

Cheers,
Benno

**Comment by rkansal47** [comment]
Oh interesting, thanks for pointing this out. Just so I understand first, what are you changing between the 30 plots? And could you share the code for creating the different `t` and `q` and `g` arrays as well?

**Comment by kaechb** [comment]
Hi, I am plotting the 30 particles, so the first plot is the hardest particle, and the last one the softest. So the code for loading the datasets is quite simple:
```
q=pd.read_csv("q_jets.csv",header=None,sep=" ")
t=pd.read_csv("t_jets.csv",header=None,sep=" ")
g=pd.read_csv("g_jets.csv",header=None,sep=" ")
q=q.values.reshape(-1,30,4)
g=g.values.reshape(-1,30,4)
t=t.values.reshape(-1,30,4)
```
And the csv are just the ones I download with e.g. `wget https://zenodo.org/record/4834876/files/t_jets.csv\?download\=1`

**Comment by kaechb** [comment]
The $\phi, \eta$ look fine btw, for the top the distribution they are just broader for the different particles w.r.t. gluon and light quarks

**Comment by rkansal47** [comment]
I see, I think what this is showing is that the jet fragmentation distribution (defined e.g. [here](https://cds.cern.ch/record/2254861/files/1512294_73-78.pdf) is higher for light quark jets than gluon and top quark jets, which is what we would expect, so I believe the data is correct.

Or to put it another way, you can see in Fig. 3 in https://arxiv.org/abs/2106.11535 that the overall jet multiplicity is lower, and the relative $\eta$ distribution is narrower, for light quark jets (again, as we would expect). Since the total jet $p_T$ for all the jets is about the same at ~1TeV, that means the hardest light quark jet constituents must have higher $p_T$ than in gluon and top quark jets.

**Comment by kaechb** [comment]
Oh, I never thought of it like that. But wouldn't that mean, that it is super easy to build a gluon/quark jet tagger?
Also the distributions of the multiplicities are not that different:
![image](https://user-images.githubusercontent.com/38372086/187934312-ddcde6f2-a03a-4357-b782-7239daabf979.png)


Cheers,
Benno

**Comment by rkansal47** [comment]
Perhaps the difference in multiplicities is more clear looking at the 150 particle dataset (JetNet150 on Zenodo)
<img width="423" alt="Screenshot 2022-09-01 at 17 55 01" src="https://user-images.githubusercontent.com/19512506/187958946-4ad29b54-23db-4d66-95fc-9e74777c5012.png">

Indeed, as discussed in e.g. [this paper](https://cds.cern.ch/record/2254861/files/1512294_73-78.pdf) the jet multiplicity, angular distribution, and jet fragmentation distribution are three of the main handles we have in discriminating g vs q jets, however the distributions of all three variables still have significant overlap so it is not so simple.

**Comment by kaechb** [comment]
Oh, so could it also be that this difference also only becomes very relevant if we look at 1 TeV jets? 
My point was if we look at my plot, and take e.g. the 26. particle. Just based on the $p_T$ distribution there we could discriminate quite well right? So in that case building a quark gluon tagger would be super easy but since usually the jets are not that energetic it is not possible. 
Anyhow many thanks for the explanation!
