### ISSUE TITLE
Splits for comparison

### ISSUE THREAD

**Issue by kaechb** [jet-net/JetNet#22]
Hi Raghav,
I was working until now with version 1.1 of the Zenodo dataset and the JetNet version 0.1.1
So now I have seen that you have introduced a test split - however, in order to compare to your previous paper I have used the default settings of JetNet 0.1.1 during evaluation and the default train/validation split (which is a 70/30 split as in the publication) - would you prefer if future publications publish their scores on the test set or should the same 70/30 split be used?
Cheers and Thanks,
Benno

**Comment by rkansal47** [comment]
Hi Benno, that's a good question. Better practice is probably to pick the best model based on the scores on the validation dataset and then report the scores on the unused test dataset. The issue though is that FPND needs ~50,000 samples to be accurate, so we would need to use at least ~30% of the total samples per class in JetNet for the validation and testing datasets each. This is why we went with the 70/30 split. If you can afford to do a 40/30/30 training/validation/testing split, that might be the best solution but, if not, 70/30 should be fine.

**Comment by kaechb** [comment]
Thanks for the quick reply! The problem with the FPND is that I can't really access it, since the activations for the real sample are saved. So I guess for now I'll stick to the 70/30 split but I'll try and see how far the 40/30/30 gets me, that is a nice idea.
