### ISSUE TITLE
Wrong indexing in w1p mask

### ISSUE THREAD

**Issue by mova** [jet-net/JetNet#29]
https://github.com/jet-net/JetNet/blob/85155bda2789e19a6d9084c053ac34224124fb5e/jetnet/evaluation/gen_metrics.py#L359

This should probably be 
`mask2 = mask2.reshape(jets2.shape[0], jets2.shape[1])`
like for the first mask.

Cheers

**Comment by rkansal47** [comment]
Thanks, fixed this as part of #30.
