### ISSUE TITLE
Comments from jpata

### ISSUE THREAD

**Issue by jpata** [jet-net/JetNet#43]
Nice package! The following items came up when reading the text.

Repository:
- [x] community guidelines: consider adding a CONTRIBUTING.md document with guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Paper:
- [x] State of the field: consider describing briefly how this package compares to other commonly used packages, for example `pytorch-fid`, `energyflow`. Are there parts that are copied verbatim from other packages (with API unifications)?

I will check the functionality later, so I will update this issue.

**Comment by rkansal47** [comment]
Thank you for the comments @jpata! I believe we have incorporated both suggestions.
